apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: first-component
  description: First backstage component
  tags:
    - go
    - website
spec:
  type: service
  lifecycle: production
  owner: guests
